# Generated by Django 5.0.6 on 2024-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tipo_pago', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_pago', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fch_pago', models.DateField()),
                ('id_tram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tramite')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.tipopago')),
            ],
        ),
    ]
