# Generated by Django 5.0.6 on 2024-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tipo_inci', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fch_rep_inc', models.DateField()),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.personal')),
                ('id_tipo_inci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incidentes.tipoincidente')),
            ],
        ),
    ]
