# Generated by Django 5.0.6 on 2024-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tipo_per', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_per', models.CharField(max_length=10)),
                ('name_per', models.TextField()),
                ('lname_per', models.TextField()),
                ('fch_naci_per', models.DateField()),
                ('tel1_per', models.CharField(max_length=10)),
                ('tel2_per', models.CharField(max_length=10)),
                ('id_tipo_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.tipopersonal')),
            ],
        ),
    ]
