# Generated by Django 5.0.6 on 2024-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Difuntos', '0001_initial'),
        ('Ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_clien', models.CharField(max_length=10)),
                ('name_clien', models.TextField()),
                ('lname_clien', models.TextField()),
                ('fch_naci_clien', models.DateField()),
                ('tel1_clien', models.CharField(max_length=10)),
                ('tel2_clien', models.CharField(max_length=10)),
                ('id_ubi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubicaciones.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('id_difu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Difuntos.difunto')),
            ],
        ),
    ]
