# Generated by Django 5.0.6 on 2024-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_can', models.TextField()),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubicaciones.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubicaciones.canton')),
                ('id_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubicaciones.provincia')),
            ],
        ),
    ]
